import { test, expect } from "@playwright/test";
import { login } from "../helpers/login";

test("User can add a new guide successfully", async ({ page, baseURL }) => {
  await login(page, baseURL);

  await page.goto("/guides");
  await page.waitForLoadState("domcontentloaded");
  await page.waitForTimeout(300);

  const addButton = page.getByRole("button", { name: "+" });
  await expect(addButton).toBeVisible();
  await addButton.click({ force: true });

  await page.waitForSelector("h2:text('Add New Guide')", { timeout: 7000 });
  const modalTitle = page.getByRole("heading", { name: /add new guide/i });
  await expect(modalTitle).toBeVisible();

  const uniqueTitle = `Playwright Guide ${Date.now()}`;

  // Fill
  await page.getByLabel("Title*", { exact: false }).fill(uniqueTitle);
  await page
    .getByLabel("Description", { exact: false })
    .fill("This is a test description generated by Playwright.");
  await page.getByPlaceholder("Enter step 1").fill("Step 1");
  await page.getByRole("button", { name: /\+ Add Step/i }).click();
  await page.getByPlaceholder("Enter step 2").fill("Step 2");

  await page
    .getByPlaceholder("Paste image URL")
    .fill("https://example.com/test-image.jpg");
  await page
    .getByPlaceholder("https://youtube.com/...")
    .fill("https://youtube.com/test-video");

  await page.getByLabel("Category*", { exact: false }).fill("Test");
  await page.getByLabel("Author", { exact: false }).fill("Playwright Bot");

  const toolSelector = page.locator("select").first();
  const toolOptions = await toolSelector.evaluate((sel) =>
    [...sel.options].map((o) => o.value)
  );
  if (toolOptions[1]) await toolSelector.selectOption(toolOptions[1]);

  // Submit
  const submitBtn = page.getByRole("button", { name: /add guide/i });
  await submitBtn.click();

  // Wait for modal to close
  await expect(modalTitle).toBeHidden({ timeout: 7000 });

  // Reload to fetch the new DB state
  await page.reload();
  await page.waitForLoadState("domcontentloaded");
  await page.waitForTimeout(500);

  // Reset filters
  await page.getByRole("combobox").selectOption("");
  await page.waitForTimeout(300);

  // Scroll to top (WebKit)
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.waitForTimeout(300);

  // Check new guide
  const newGuide = page.getByRole("heading", { name: uniqueTitle }).first();
  await expect(newGuide).toBeVisible({ timeout: 7000 });

  // Text assert
  await expect(page.getByText(uniqueTitle, { exact: true })).toBeVisible({
    timeout: 7000,
  });
});
